---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: --CLUSTER-NAME--
  region: --AWS_REGION--
  version: --EKS_VERSION--

availabilityZones: [--AZA--, --AZB--]

managedNodeGroups:
- amiFamily: AmazonLinux2
  instanceType: --NG-A-EC2--
  name: --NG-A-NAME--
  desiredCapacity: 2
  maxSize: 3
  minSize: 0
  labels:
    alpha.eksctl.io/cluster-name: --CLUSTER-NAME--
    alpha.eksctl.io/nodegroup-name: --NG-A-NAME--
    --NG-A-KEY--: --NG-A-VAL--
  tags:
    alpha.eksctl.io/nodegroup-name: --NG-A-NAME--
    alpha.eksctl.io/nodegroup-type: managed
    k8s.io/cluster-autoscaler/node-template/label/intent: --NG-A-LABEL--
  iam:
    withAddonPolicies:
      autoScaler: true
      cloudWatch: true
      albIngress: true
  privateNetworking: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]