---
controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: "--JENKINS-CNTRL-TAG--"
  #tag: "2.303.2-lts-jdk11"
  resources:
    requests:
      cpu: "1024m"
      memory: "4Gi"
    limits:
      cpu: "4096m"
      memory: "8Gi"

  servicePort: 80
  serviceType: LoadBalancer

  nodeSelector:
    --NG-A-KEY--: --NG-A-VAL--

serviceAccountAgent:
  create: false
